/**
 * P2 curated content plan — ~35 high-intent topics.
 * Generate as DRAFT only; human review before publish. Tie to GSC impressions when available.
 */

export type P2ContentPriority = "high" | "medium" | "low";

export type P2ContentTopic = {
  id: string;
  title: string;
  categorySlug: string;
  clusterId: string;
  searchIntent: string;
  priority: P2ContentPriority;
  relatedToolHref?: string;
  relatedGuideHref?: string;
  /** Ops: paste GSC query + impressions when promoting to pipeline */
  gscHint?: string;
  outline: string[];
};

/** Hand-curated — not auto-published. Max ~2 drafts/week from this list until GSC validates. */
export const P2_CONTENT_TOPICS: P2ContentTopic[] = [
  {
    id: "p2-sip-beginners",
    title: "SIP for Beginners in India: Step-by-Step Without Jargon",
    categorySlug: "finance",
    clusterId: "sip-investing",
    searchIntent: "SIP for beginners India how to start",
    priority: "high",
    relatedToolHref: "/tools/sip-calculator",
    outline: ["What SIP is", "Minimum amounts", "Risk disclaimer", "How to use our calculator"],
  },
  {
    id: "p2-home-loan-emi",
    title: "Home Loan EMI Planning India: Tenure vs Interest Trade-offs",
    categorySlug: "finance",
    clusterId: "emi-loans",
    searchIntent: "home loan EMI planning India",
    priority: "high",
    relatedToolHref: "/tools/emi-calculator",
    outline: ["EMI components", "Floating vs fixed", "Prepayment", "Calculator walkthrough"],
  },
  {
    id: "p2-new-tax-regime",
    title: "New Tax Regime vs Old Regime India: Which Saves More?",
    categorySlug: "finance",
    clusterId: "salary-tax",
    searchIntent: "new vs old tax regime India salaried",
    priority: "high",
    relatedToolHref: "/tools/salary-tax-calculator",
    outline: ["Slab basics", "When old wins", "When new wins", "Official portal reminder"],
  },
  {
    id: "p2-fastag-recharge",
    title: "FASTag Recharge Failed? Fix Blacklist & Low Balance Issues",
    categorySlug: "technology",
    clusterId: "fastag",
    searchIntent: "FASTag recharge failed blacklist India",
    priority: "high",
    relatedGuideHref: "/guides/schemes/fastag-india-eligibility-recharge-faq",
    outline: ["Common errors", "Issuer app steps", "NHAI resources", "Safety tips"],
  },
  {
    id: "p2-ifsc-wrong-transfer",
    title: "Sent Money to Wrong IFSC? What Indians Can Do Next",
    categorySlug: "finance",
    clusterId: "banking-ifsc",
    searchIntent: "wrong IFSC transfer what to do India",
    priority: "high",
    relatedToolHref: "/tools/ifsc-finder",
    outline: ["Immediate steps", "Bank escalation", "Prevention checklist"],
  },
  {
    id: "p2-gst-freelancer",
    title: "GST for Freelancers India: Registration Thresholds Explained",
    categorySlug: "finance",
    clusterId: "gst-business",
    searchIntent: "GST registration freelancer India threshold",
    priority: "high",
    relatedToolHref: "/tools/gst-calculator",
    outline: ["Who must register", "Composition scheme", "Invoice basics", "Portal link"],
  },
  {
    id: "p2-fd-vs-rd",
    title: "FD vs RD India: Which Fits Your Savings Goal?",
    categorySlug: "finance",
    clusterId: "sip-investing",
    searchIntent: "FD vs RD India difference",
    priority: "medium",
    relatedToolHref: "/tools/fd-calculator",
    outline: ["Liquidity", "Interest compounding", "Tax on interest", "Tool links"],
  },
  {
    id: "p2-ppf-guide",
    title: "PPF Account India: Limits, Lock-in, and Tax Benefits",
    categorySlug: "finance",
    clusterId: "sip-investing",
    searchIntent: "PPF account rules India 2026",
    priority: "medium",
    relatedToolHref: "/tools/ppf-calculator",
    outline: ["Annual cap", "Maturity", "Partial withdrawal", "Calculator use"],
  },
  {
    id: "p2-pm-kisan-status",
    title: "PM-KISAN Status Check: e-KYC & Payment Pending Fixes",
    categorySlug: "careers",
    clusterId: "govt-schemes",
    searchIntent: "PM KISAN status check payment pending",
    priority: "medium",
    relatedGuideHref: "/guides/schemes/pm-kisan-eligibility-how-to-apply",
    outline: ["Official portal", "e-KYC flags", "Common reject reasons"],
  },
  {
    id: "p2-sarkari-result",
    title: "Sarkari Result vs Scorecard: How to Read Govt Exam PDFs",
    categorySlug: "careers",
    clusterId: "govt-schemes",
    searchIntent: "how to read sarkari result scorecard",
    priority: "medium",
    relatedToolHref: "/results",
    outline: ["Provisional vs final", "Cutoff", "Document verification"],
  },
  {
    id: "p2-huid-buy-gold",
    title: "Buying Gold in India: HUID & Hallmark Checklist Before You Pay",
    categorySlug: "finance",
    clusterId: "banking-ifsc",
    searchIntent: "HUID hallmark gold buying checklist India",
    priority: "high",
    relatedToolHref: "/huid-verification",
    outline: ["22K vs 24K", "HUID scan", "Invoice items", "Red flags"],
  },
  {
    id: "p2-credit-score-india",
    title: "Credit Score India: What Actually Moves CIBIL (No Myths)",
    categorySlug: "finance",
    clusterId: "emi-loans",
    searchIntent: "improve credit score India CIBIL",
    priority: "medium",
    outline: ["Utilisation", "On-time EMIs", "Hard inquiries", "Not financial advice"],
  },
  {
    id: "p2-upi-fraud",
    title: "UPI Fraud India: OTP Scams & How to Report on NPCI Rails",
    categorySlug: "technology",
    clusterId: "banking-ifsc",
    searchIntent: "UPI fraud report India what to do",
    priority: "high",
    outline: ["Scam patterns", "Bank freeze", "Cybercrime portal", "Prevention"],
  },
  {
    id: "p2-ott-where-watch",
    title: "Where to Watch New Movies in India: OTT vs Cinema Legal Guide",
    categorySlug: "movies",
    clusterId: "govt-schemes",
    searchIntent: "where to watch movie OTT India legal",
    priority: "medium",
    relatedGuideHref: "/cineverse",
    outline: ["Theatre window", "OTT platforms", "CineVerse hub link"],
  },
  {
    id: "p2-cricket-scorecard",
    title: "How to Read a Cricket Scorecard: Overs, Run Rate & DLS Basics",
    categorySlug: "sports",
    clusterId: "govt-schemes",
    searchIntent: "how to read cricket scorecard run rate",
    priority: "low",
    relatedToolHref: "/sports",
    outline: ["Batting card", "Bowling figures", "Live hub link"],
  },
  {
    id: "p2-phonepe-budget",
    title: "Track PhonePe & GPay Spends: Monthly Budget Workflow",
    categorySlug: "finance",
    clusterId: "emi-loans",
    searchIntent: "track UPI expenses India budget",
    priority: "medium",
    relatedToolHref: "/moneyverse",
    outline: ["Screenshot scan", "Categories", "Weekly review habit"],
  },
  {
    id: "p2-bank-statement-pdf",
    title: "Bank Statement PDF Analysis: What to Check Before a Loan",
    categorySlug: "finance",
    clusterId: "emi-loans",
    searchIntent: "bank statement analysis loan India",
    priority: "medium",
    relatedToolHref: "/moneyverse/bank-statement-analyzer",
    outline: ["Avg balance", "Bounces", "Privacy", "Tool limits"],
  },
  {
    id: "p2-fuel-highway",
    title: "Highway Fuel Planning India: FASTag, Stops & Cost Buffer",
    categorySlug: "travel",
    clusterId: "travel-fuel",
    searchIntent: "highway trip fuel cost India planning",
    priority: "medium",
    relatedToolHref: "/tools/fuel-price",
    relatedGuideHref: "/guides/schemes/fastag-india-eligibility-recharge-faq",
    outline: ["Route litres", "Pump timing", "FASTag balance"],
  },
  {
    id: "p2-pincode-ecommerce",
    title: "Wrong Pincode on Amazon/Flipkart Orders: Fix Before Dispatch",
    categorySlug: "technology",
    clusterId: "banking-ifsc",
    searchIntent: "wrong pincode order India fix",
    priority: "low",
    relatedToolHref: "/tools/pincode-finder",
    outline: ["Edit window", "India Post zones", "COD risks"],
  },
  {
    id: "p2-rto-used-car",
    title: "Used Car RC Check India: RTO Codes vs Official Vahan Steps",
    categorySlug: "technology",
    clusterId: "travel-fuel",
    searchIntent: "used car RC verification India",
    priority: "medium",
    relatedToolHref: "/tools/rto-finder",
    outline: ["Public RTO decode", "Vahan auth", "Hypothecation"],
  },
  {
    id: "p2-chatgpt-students",
    title: "ChatGPT for Indian Students: Prompts That Save Time (Safely)",
    categorySlug: "technology",
    clusterId: "govt-schemes",
    searchIntent: "ChatGPT students India how to use",
    priority: "medium",
    relatedToolHref: "/ai",
    outline: ["Study prompts", "Plagiarism caution", "ContentVerse AI link"],
  },
  {
    id: "p2-merge-pdf-work",
    title: "Merge PDF for Job Applications: Size Limits & Mobile Tips",
    categorySlug: "technology",
    clusterId: "govt-schemes",
    searchIntent: "merge PDF job application India mobile",
    priority: "low",
    relatedToolHref: "/tools/merge-pdf",
    outline: ["File size", "Order pages", "Govt form uploads"],
  },
  {
    id: "p2-silver-rate",
    title: "Silver Rate Today India: How Retail Prices Differ by City",
    categorySlug: "finance",
    clusterId: "sip-investing",
    searchIntent: "silver rate today India city",
    priority: "low",
    relatedToolHref: "/tools/silver-rate",
    outline: ["Spot vs retail", "Making charges", "GoldVerse cross-link"],
  },
  {
    id: "p2-nifty-beginners",
    title: "Nifty & Sensex for Beginners: Index vs Mutual Funds",
    categorySlug: "finance",
    clusterId: "sip-investing",
    searchIntent: "Nifty Sensex explained beginners India",
    priority: "medium",
    relatedToolHref: "/finance",
    outline: ["What an index is", "ETF vs active", "Live ticker hub"],
  },
  {
    id: "p2-expense-tracker-salary",
    title: "50-30-20 Budget on Indian Salaries: A Practical Template",
    categorySlug: "finance",
    clusterId: "emi-loans",
    searchIntent: "50 30 20 rule India salary budget",
    priority: "medium",
    relatedToolHref: "/moneyverse",
    outline: ["Rent in metros", "EMI bucket", "SIP bucket", "Tool workflow"],
  },
  {
    id: "p2-hra-tax",
    title: "HRA Exemption India: Documents Your CA Will Ask For",
    categorySlug: "finance",
    clusterId: "salary-tax",
    searchIntent: "HRA exemption documents India",
    priority: "medium",
    relatedToolHref: "/tools/salary-tax-calculator",
    outline: ["Metro vs non-metro", "Rent receipts", "Old regime only"],
  },
  {
    id: "p2-section-80c",
    title: "Section 80C Options India: ELSS, PPF, LIC — Compare Simply",
    categorySlug: "finance",
    clusterId: "salary-tax",
    searchIntent: "section 80C options comparison India",
    priority: "medium",
    outline: ["₹1.5L cap", "Lock-in periods", "Not product recommendations"],
  },
  {
    id: "p2-gold-loan",
    title: "Gold Loan vs Personal Loan India: When Each Makes Sense",
    categorySlug: "finance",
    clusterId: "emi-loans",
    searchIntent: "gold loan vs personal loan India",
    priority: "low",
    relatedToolHref: "/tools/emi-calculator",
    outline: ["LTV", "Interest rates", "Repossession risk"],
  },
  {
    id: "p2-digital-arrest",
    title: "Digital Arrest Scams India: Red Flags & Cybercrime Reporting",
    categorySlug: "technology",
    clusterId: "govt-schemes",
    searchIntent: "digital arrest scam India what to do",
    priority: "high",
    outline: ["Script patterns", "1930 helpline", "Do not pay"],
  },
  {
    id: "p2-aadhaar-update",
    title: "Aadhaar Update Online: Address vs Mobile — Common Errors",
    categorySlug: "technology",
    clusterId: "govt-schemes",
    searchIntent: "Aadhaar update online address mobile",
    priority: "medium",
    outline: ["UIDAI portal", "Appointment", "SC/ST fee waivers if relevant"],
  },
  {
    id: "p2-ayushman-eligibility",
    title: "Ayushman Bharat Eligibility: Who Gets PM-JAY Benefits",
    categorySlug: "health",
    clusterId: "govt-schemes",
    searchIntent: "Ayushman Bharat eligibility PM-JAY",
    priority: "medium",
    outline: ["SECC list", "Hospital empanelment", "Official site only"],
  },
  {
    id: "p2-mutual-fund-exit",
    title: "When to Exit a Mutual Fund SIP: Rebalance Without Panic",
    categorySlug: "finance",
    clusterId: "sip-investing",
    searchIntent: "when to stop SIP mutual fund India",
    priority: "medium",
    relatedToolHref: "/tools/sip-calculator",
    outline: ["Goal-based exit", "Tax on STCG/LTCG", "SEBI disclaimer"],
  },
  {
    id: "p2-credit-card-minimum",
    title: "Credit Card Minimum Due Trap: True Cost in India",
    categorySlug: "finance",
    clusterId: "emi-loans",
    searchIntent: "credit card minimum due interest India",
    priority: "medium",
    outline: ["APR math", "EMI conversion", "Not lending advice"],
  },
  {
    id: "p2-work-from-home-tax",
    title: "Work From Home Tax Benefits India: Internet & Furniture",
    categorySlug: "finance",
    clusterId: "salary-tax",
    searchIntent: "work from home tax deduction India",
    priority: "low",
    relatedToolHref: "/tools/salary-tax-calculator",
    outline: ["Employer allowance", "Old regime", "Form 16 lines"],
  },
  {
    id: "p2-content-creator-tax",
    title: "Income Tax for Content Creators India: GST, TDS & Invoices",
    categorySlug: "finance",
    clusterId: "gst-business",
    searchIntent: "content creator tax India GST TDS",
    priority: "medium",
    outline: ["Section 194R", "GST threshold", "Record keeping"],
  },
  {
    id: "p2-creator-monetization",
    title: "ContentVerse Creator Monetization: Tips, Moderation & Quality",
    categorySlug: "technology",
    clusterId: "govt-schemes",
    searchIntent: "ContentVerse India creator earn",
    priority: "low",
    relatedToolHref: "/creator-program",
    outline: ["Moderation", "Ad eligibility", "Quality bar"],
  },
];

export function getP2TopicsByPriority(priority?: P2ContentPriority) {
  if (!priority) return P2_CONTENT_TOPICS;
  return P2_CONTENT_TOPICS.filter((t) => t.priority === priority);
}

export function getP2TopicById(id: string) {
  return P2_CONTENT_TOPICS.find((t) => t.id === id);
}
